### ISSUE TITLE
What is the code license?

### ISSUE THREAD

**Issue by Liam-Deacon** [jisaacstone/odata-py#1]
Hi @jisaacstone - this looks like a really interesting project. The ODATA v4 standard is huge and kudos for your approach (I particularly like the use of parsley to translate query -> sql grammar - genius!) 👍  

My only question is, what is the license for this library?

Thanks,

Liam

**Comment by jisaacstone** [comment]
hey yeah I forgot to put in. Added MIT license for ya.

We moved away from python and odata before I got a chance to use it in production, but there is a solid foundation here IIRC
